# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pywordlesolver_psgui',
                'doc_host': 'https://artyb.github.io',
                'git_url': 'https://github.com/artyb/pywordlesolver_psgui',
                'lib_path': 'pywordlesolver_psgui'},
  'syms': {'pywordlesolver_psgui.core': {'pywordlesolver_psgui.core.foo': ('core.html#foo', 'pywordlesolver_psgui/core.py')}}}